'use client'

import { useState, useEffect, useCallback } from 'react'
import { RiskMeter } from '@/components/risk-meter'
import { AlertFeed } from '@/components/alert-feed'
import { FinancialExposurePanel } from '@/components/financial-exposure-panel'
import { AISafetySummary } from '@/components/ai-safety-summary'
import { NetworkGraph } from '@/components/network-graph'
import { ArrowLeft, Activity, RefreshCw, FileText, Download } from 'lucide-react'
import type {
  RiskScore,
  Alert,
  ContainmentStatus,
  FinancialExposure,
  GeminiUserExplanation,
  NetworkGraph as NetworkGraphType,
  UnifiedEvent,
} from '@/lib/types'

interface UserDashboardData {
  accountId: string
  riskScore: RiskScore
  alerts: Alert[]
  containment: ContainmentStatus
  financialExposure: FinancialExposure
  geminiUserExplanation: GeminiUserExplanation | null
  network: NetworkGraphType
  recentEvents: UnifiedEvent[]
}

interface UserDashboardProps {
  onBack: () => void
}

export function UserDashboard({ onBack }: UserDashboardProps) {
  const [data, setData] = useState<UserDashboardData | null>(null)
  const [aiLoading, setAiLoading] = useState(false)
  const [reportLoading, setReportLoading] = useState(false)
  const [tickCount, setTickCount] = useState(0)

  const fetchDashboard = useCallback(async () => {
    try {
      await fetch('/api/simulate')
      const res = await fetch('/api/user/dashboard')
      if (res.ok) {
        const dashData = await res.json()
        setData(dashData)
        setTickCount(prev => prev + 1)
      }
    } catch (err) {
      console.error('User dashboard fetch error:', err)
    }
  }, [])

  const triggerUserAI = useCallback(async () => {
    if (!data) return
    setAiLoading(true)
    try {
      const res = await fetch('/api/gemini/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          mode: 'user',
          cyberSignals: data.recentEvents.flatMap(e => e.cyberSignals).slice(0, 3),
          transactionData: data.recentEvents.flatMap(e => e.transactionData).slice(0, 3),
          riskScore: data.riskScore?.unifiedScore || 0,
        }),
      })
      if (res.ok) {
        const explanation = await res.json()
        setData(prev => prev ? { ...prev, geminiUserExplanation: explanation } : null)
      }
    } catch (err) {
      console.error('User AI error:', err)
    } finally {
      setAiLoading(false)
    }
  }, [data])

  const generateReport = useCallback(async () => {
    setReportLoading(true)
    try {
      const res = await fetch('/api/report')
      if (res.ok) {
        const report = await res.json()
        // Generate downloadable text report
        const reportText = `
═══════════════════════════════════════════════
          LAYERLOCK INCIDENT REPORT
═══════════════════════════════════════════════

${report.title || 'Incident Report'}
Generated: ${report.generatedAt || new Date().toISOString()}
Account: ${report.accountId || 'N/A'}
Risk Score: ${report.riskScore || 0}/100

───────────────────────────────────────────────
INCIDENT SUMMARY
───────────────────────────────────────────────
${report.incidentSummary}

───────────────────────────────────────────────
RISK EXPLANATION
───────────────────────────────────────────────
${report.riskExplanation}

───────────────────────────────────────────────
ACTIONS TAKEN
───────────────────────────────────────────────
${report.actionsTaken}

───────────────────────────────────────────────
NETWORK SUMMARY
───────────────────────────────────────────────
${report.networkSummary}

───────────────────────────────────────────────
RECOMMENDATIONS
───────────────────────────────────────────────
${report.recommendations}

═══════════════════════════════════════════════
This report was auto-generated by LayerLock AI.
═══════════════════════════════════════════════
`.trim()

        const blob = new Blob([reportText], { type: 'text/plain' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `layerlock-incident-report-${Date.now()}.txt`
        a.click()
        URL.revokeObjectURL(url)
      }
    } catch (err) {
      console.error('Report generation error:', err)
    } finally {
      setReportLoading(false)
    }
  }, [])

  useEffect(() => {
    fetchDashboard()
    const interval = setInterval(fetchDashboard, 5000)
    return () => clearInterval(interval)
  }, [fetchDashboard])

  useEffect(() => {
    if (tickCount > 0 && tickCount % 3 === 0) {
      triggerUserAI()
    }
  }, [tickCount, triggerUserAI])

  if (!data) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="flex items-center gap-3 text-neon-blue">
          <RefreshCw className="w-6 h-6 animate-spin" />
          <span className="font-mono text-lg">Loading Your Dashboard...</span>
        </div>
      </div>
    )
  }

  const statusLabel = data.riskScore?.unifiedScore >= 75
    ? 'At Risk - Under Protection'
    : data.riskScore?.unifiedScore >= 50
      ? 'Elevated Monitoring'
      : data.riskScore?.unifiedScore >= 25
        ? 'Moderate Activity'
        : 'Secure'

  const statusColor = data.riskScore?.unifiedScore >= 75
    ? 'text-risk-high'
    : data.riskScore?.unifiedScore >= 50
      ? 'text-risk-medium'
      : data.riskScore?.unifiedScore >= 25
        ? 'text-neon-blue'
        : 'text-chart-5'

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 border-b border-border bg-background/90 backdrop-blur-md">
        <div className="flex items-center justify-between px-6 py-3">
          <div className="flex items-center gap-4">
            <button onClick={onBack} className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors cursor-pointer">
              <ArrowLeft className="w-4 h-4" />
              <span className="text-sm font-mono">Exit</span>
            </button>
            <div className="h-5 w-px bg-border" />
            <h1 className="text-lg font-bold text-foreground">
              Layer<span className="text-neon-blue">Lock</span>
              <span className="text-sm font-normal text-muted-foreground ml-3">Personal Dashboard</span>
            </h1>
          </div>
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2">
              <Activity className="w-4 h-4 text-chart-5 animate-pulse" />
              <span className="text-xs font-mono text-muted-foreground">MONITORING</span>
            </div>
            <button
              onClick={generateReport}
              disabled={reportLoading}
              className="flex items-center gap-2 px-3 py-1.5 text-xs font-mono bg-secondary text-foreground border border-border rounded-lg hover:bg-muted transition-colors disabled:opacity-50 cursor-pointer"
            >
              {reportLoading ? <RefreshCw className="w-3 h-3 animate-spin" /> : <Download className="w-3 h-3" />}
              Download Report
            </button>
          </div>
        </div>
      </header>

      {/* Dashboard */}
      <div className="p-4 lg:p-6 max-w-6xl mx-auto">
        {/* Account status banner */}
        <div className="rounded-xl border border-border bg-card p-6 mb-6">
          <div className="flex flex-col md:flex-row items-center gap-6">
            <RiskMeter score={data.riskScore?.unifiedScore || 0} size="md" />
            <div className="flex-1 text-center md:text-left">
              <p className="text-sm font-mono text-muted-foreground mb-1">Account {data.accountId}</p>
              <h2 className="text-2xl font-bold text-foreground mb-2 text-balance">Account Status</h2>
              <p className={`text-lg font-semibold font-mono ${statusColor}`}>{statusLabel}</p>
            </div>
            <div className="flex items-center gap-2 px-4 py-2 rounded-lg bg-secondary border border-border">
              <FileText className="w-4 h-4 text-muted-foreground" />
              <span className="text-xs font-mono text-muted-foreground">
                {data.recentEvents.length} recent events
              </span>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Left - AI Summary + Financial */}
          <div className="lg:col-span-5 flex flex-col gap-6">
            <AISafetySummary explanation={data.geminiUserExplanation} loading={aiLoading} />
            <FinancialExposurePanel exposure={data.financialExposure} />
          </div>

          {/* Right - Network + Alerts */}
          <div className="lg:col-span-7 flex flex-col gap-6">
            <NetworkGraph network={data.network} compact />

            <div className="rounded-xl border border-border bg-card p-4">
              <h3 className="text-sm font-semibold font-mono uppercase tracking-wider text-foreground mb-3">
                Recent Alerts
              </h3>
              <AlertFeed alerts={data.alerts} maxItems={6} />
            </div>

            {/* Incident timeline */}
            <div className="rounded-xl border border-border bg-card p-4">
              <h3 className="text-sm font-semibold font-mono uppercase tracking-wider text-foreground mb-3">
                Incident Timeline
              </h3>
              <div className="flex flex-col gap-3">
                {data.recentEvents.length === 0 ? (
                  <p className="text-sm text-muted-foreground">No recent incidents.</p>
                ) : (
                  data.recentEvents.map((event) => (
                    <div key={event.id} className="flex items-start gap-3">
                      <div className="flex flex-col items-center">
                        <div
                          className="w-3 h-3 rounded-full border-2 shrink-0"
                          style={{
                            borderColor: event.riskScore >= 75 ? '#EF4444' : event.riskScore >= 50 ? '#F59E0B' : '#00D4FF',
                            backgroundColor: event.riskScore >= 75 ? 'rgba(239,68,68,0.2)' : 'transparent',
                          }}
                        />
                        <div className="w-px h-6 bg-border" />
                      </div>
                      <div className="flex flex-col gap-0.5 pb-2">
                        <p className="text-sm text-foreground">
                          Risk score reached <span className="font-mono font-semibold">{event.riskScore}</span> with{' '}
                          {event.cyberSignals.length} cyber + {event.transactionData.length} transaction signals
                        </p>
                        <span className="text-xs font-mono text-muted-foreground">
                          {new Date(event.timestamp).toLocaleTimeString()}
                        </span>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
